String​.prototype​.anchor()
String​.prototype​.big()
String​.prototype​.blink()
String​.prototype​.bold()
String​.prototype​.charAt()
// String​.prototype​.char​CodeAt()
// String​.prototype​.code​PointAt()
String​.prototype​.concat()
// String​.prototype​.ends​With()

String​.prototype​.fixed()
String​.prototype​.fontcolor()
String​.prototype​.fontsize()
String​.prototype​.includes()
String.prototype.indexOf()
String​.prototype​.italics()
// String​.prototype​.last​IndexOf()
String​.prototype​.link()
// String​.prototype​.locale​Compare()
String​.prototype​.match()
String​.prototype​.matchAll()
String​.prototype​.normalize()
String​.prototype​.padEnd()
// String​.prototype​.pad​Start()

String​.prototype​.repeat()
String​.prototype​.replace()
String​.prototype​.search()
String​.prototype​.slice()
String​.prototype​.small()
String​.prototype​.split()
// String​.prototype​.starts​With()
String​.prototype​.strike()
String​.prototype​.sub()
String​.prototype​.substr()
String​.prototype​.substring()
String​.prototype​.sup()
// String​.prototype​.toLocale​Lower​Case()

// String​.prototype​.toLower​Case()
String​.prototype​.toSource()
String​.prototype​.toString()
// String​.prototype​.toUpper​Case()
String​.prototype​.trim()
String​.prototype​.trimEnd()
// String​.prototype​.trim​Start()
String​.prototype​.valueOf()
String​.raw()